package com.coach.plugin.events;

public enum EventType
{
	TICK,
	ANIMATION_CHANGED,
	PROJECTILE_MOVED,
	GRAPHIC_CHANGED,
	GRAPHICS_OBJECT_CREATED,
	NPC_SPAWNED,
	NPC_DESPAWNED,
	PLAYER_STATS_CHANGED,
	VARBIT_CHANGED,
	ITEM_CONTAINER_CHANGED,
	CHAT_MESSAGE
}
